### ISSUE TITLE
The `Text signal should be a list of strings, etc.

### ISSUE THREAD

**Issue by dbuenzli** [aantron/markup.ml#1]
That is:

```ocaml
`Text of string list 
```

This allows you to return normalized streams while not failing on 32-bits platforms where the size of strings is severly limited (16MB). This is an issue in practice on 32-bit platforms see for example [this comment](https://github.com/xapi-project/xen-api/blob/c2f7a08973b37e4f5f031dab59e012556266f03b/ocaml/xapi/wlb_reports.ml#L28-L30) about xmlm in the `xen-api` project.

I didn't have close look at your code so I don't know if you are handling this correctly but be aware that adding to a `Buffer` raises `Failure _ ` if the add exceeds `Sys.max_string_length`, which is something you hit very quickly on 32-bits platforms. For this reason I have a `Max_buffer_size case in Xmlm's [error](http://erratique.ch/software/xmlm/doc/Xmlm#TYPEerror) type but of course this is not the right way of solving the problem... The above suggestion is.

**Comment by aantron** [comment]
Thanks for making me aware of this. In fact, I don't handle the issue with buffer size. I will give some thought as to what is the best way to deal with this in terms of the interface. Perhaps I will make some alternative or polymorphic signal type, and default to "simple" signals. Or maybe `string list` is fine for everyone...

**Comment by aantron** [comment]
There is also the possibility of using
```ocaml
Text of (char, ?) stream
```
though this would have considerable complications, including the facts that streams are currently ephemeral and parametrized over how `next` completes.

**Comment by dbuenzli** [comment]
> Perhaps I will make some alternative or polymorphic signal type, and default to "simple" signals. Or maybe string list is fine for everyone...

I'd keep it simple and make the string list for everyone. It also makes the client aware that he needs to deal with this. In processing, these text nodes are likely to flow to other outputs/processes (i.e. you are unlikely to match on it); these ones will simply have to output a list of strings rather than a single string, so it will make it more robust for everyone down to the end-user which can really throw arbitrary documents to programs using your library and not hit stupid limitations on 32-bit platforms.

**Comment by aantron** [comment]
What is your opinion on using consecutive `Text` signals for this? I would be against because it complicates tree assembly code and violates some structural requirement on markup (which I don't remember where I read).

**Comment by dbuenzli** [comment]
> What is your opinion on using consecutive Text signals for this?

Clearly against, this complicates the life of everyone who parses the stream of signals. It's the library that should solve the problem for everyone.

**Comment by dbuenzli** [comment]
Also I would not include ``` `Doctype``` and ``` `Xml``` in signals, they will constantly get in your way during stream processing under the form of match branches with `assert` false. Simply parse them and tuple the information with a stream of signals that represents only the content.

**Comment by aantron** [comment]
Has this been observed as a problem with Xmlm?

I believe the `PI signal in Markup.ml needs the target namespaced.

**Comment by aantron** [comment]
Also, I think many people won't be interested in the `Comment and `PI signals, but it's hard to take them out of the stream. Maybe it's better to leave in `Xml and `Doctype, but provide a filter that produces a stream of only element and text signals, and has type restricted to only those.

**Comment by dbuenzli** [comment]
Comment and PI signals are important if one wants to be able to write xml filters (something that is missing in xmlm). Providing a typed filter to cleanup the stream to get only the content seems a good solution to the problem.
