### ISSUE TITLE
Ability to ask for a specific namespace

### ISSUE THREAD

**Issue by Drup** [aantron/markup.ml#12]
`~context` in `parse_html` allows to specify the surrounding element. Instead of the surround element, I would like to ask for a specific namespace. ``~context:(`Namespace Ns.html)``, for example.

Would it error out if elements are not in the namespace ? Like if I try to parse `"<g></g>"` with an `html` namespace ?

**Comment by aantron** [comment]
Closing this, as TyXML ended up dealing with this in a different way:

Except in the case of `<a>` elements, Markup.ml always infers the XML namespace. So, this can be done by letting Markup.ml parse, then checking the namespace of top-level elements against the expected namespace.

For `<a>` elements, HTML is the default, and SVG can be requested using ``~context:(`Fragment "svg")``.
