### ISSUE TITLE
Cannot compile markup 0.7.2+uutf 1.0.0

### ISSUE THREAD

**Issue by akabe** [aantron/markup.ml#14]
Hi,

markup.ml is a very cool library, but it seems not to be support the latest version of uutf. I failed installing markup 0.7.2+uutf 1.0.0 (by using opam):

```
bash-3.2$ opam install uutf.1.0.0
opam install uutf.1.0.0
The following actions will be performed:
  ↗  upgrade   uutf   0.9.4 to 1.0.0
  ↻  recompile markup 0.7.2                   [uses uutf]
===== ↻  1   ↗  1 =====
Do you want to continue ? [Y/n] y

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
[uutf] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
⊘  removed   markup.0.7.2
⊘  removed   uutf.0.9.4
∗  installed uutf.1.0.0
[ERROR] The compilation of markup failed at "make build".
Processing  4/4: [markup: ocamlfind remove]
#=== ERROR while installing markup.0.7.2 ======================================#
# opam-version 1.2.2
# os           darwin
# command      make build
# path         /Users/akabe/.opam/4.03.0/build/markup.0.7.2
# compiler     4.03.0
# exit-code    2
# env-file     /Users/akabe/.opam/4.03.0/build/markup.0.7.2/markup-72623-2c871f.env
# stdout-file  /Users/akabe/.opam/4.03.0/build/markup.0.7.2/markup-72623-2c871f.out
# stderr-file  /Users/akabe/.opam/4.03.0/build/markup.0.7.2/markup-72623-2c871f.err
### stdout ###
# [...]
# ocamlbuild -use-ocamlfind -j 0 -no-links -cflags -g,-w,+A-4-9-44-45-48,-warn-error,+A-3,-bin-annot,-safe-string markup.cma markup.cmxa
# ocamlfind ocamldep -package uutf -modules src/markup.mli > src/markup.mli.depends
# ocamlfind ocamldep -package uutf -modules src/kstream.mli > src/kstream.mli.depends
# ocamlfind ocamldep -package uutf -modules src/common.ml > src/common.ml.depends
# ocamlfind ocamlc -c -g -w +A-4-9-44-45-48 -warn-error +A-3 -bin-annot -safe-string -package uutf -I src -I test -I doc -I test/performance -I test/pages -I test/js_of_ocaml -I test/dependency -o src/common.cmo src/common.ml
# + ocamlfind ocamlc -c -g -w +A-4-9-44-45-48 -warn-error +A-3 -bin-annot -safe-string -package uutf -I src -I test -I doc -I test/performance -I test/pages -I test/js_of_ocaml -I test/dependency -o src/common.cmo src/common.ml
# File "src/common.ml", line 137, characters 21-22:
# Error: This expression has type int but an expression was expected of type
#          Uchar.t
# Command exited with code 2.
### stderr ###
# make: *** [build] Error 10



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫 
The following actions failed
  ∗  install markup 0.7.2
The following changes have been performed
  ⊘  remove  markup 0.7.2         
  ↗  upgrade uutf   0.9.4 to 1.0.0

The former state can be restored with:
    opam switch import "~/.opam/4.03.0/backup/state-20161030052313.export"
```

Building markup 0.7.2+uutf 0.9.4 succeeded.

**Comment by aantron** [comment]
@akabe thanks. Will update the existing `opam` files to require uutf < 1.0.0, and also make a new release of Markup.ml that supports uutf 1.0.0 shortly afterwards.

**Comment by dbuenzli** [comment]
Not sure what is going on here. This should have been done in https://github.com/ocaml/opam-repository/commit/10aec7d8b928ebc52c6f4bf8b361ff323a1c8efe. @akabe did you `opam update` ?

**Comment by dbuenzli** [comment]
> This should have been done in ocaml/opam-repository@10aec7d. @akabe did you opam update ?

Well it seems a few releases went through afterwards without me noticing.

**Comment by aantron** [comment]
Hmmm. It seems that if I take the simple approach, the next Markup.ml release will only be compatible with OCaml >= 4.01, as this is a constraint in Uutf 1.0.0. I suppose this is not a great crime.

> Well it seems a few releases went through afterwards without me noticing.

But all the `markup` releases seem to have been covered correctly. But shouldn't the constraint have been `< 1.0.0`?

**Comment by dbuenzli** [comment]
> But all the markup releases seem to have been covered correctly.

Indeed, I overlooked the patch.

> But shouldn't the constraint have been < 1.0.0?

`<= 0.9.4` should be fine. If I try to install `markup` here it tries to downgrade `uutf`. I don't know.

**Comment by akabe** [comment]
@aantron Thanks for the patch!

@dbuenzli I remove `testing` opam repository (for debugging config files of my packages) and `opam update`, then constraint `uutf <= 0.94` works successfully. Thanks.

**Comment by aantron** [comment]
Markup 0.7.3, compatible with Uutf 1.0.0, is now installable from OPAM (after `opam update`, of course): https://github.com/ocaml/opam-repository/pull/7966. Thanks again for opening this issue.
