### ISSUE TITLE
Error: Library "oUnit" not found.

### ISSUE THREAD

**Issue by rwmjones** [aantron/markup.ml#49]
```
File "test/lwt_unix/dune", line 3, characters 37-42:
3 |  (libraries lwt.unix markup-lwt.unix oUnit test_support)
                                         ^^^^^
Error: Library "oUnit" not found.
```
(This appears in 3 places in the source)

I fixed this by changing these to `ounit2`.  I'm not clear if that is correct, but it made the tests pass.

**Comment by aantron** [comment]
Thanks. It's because of this: https://github.com/gildor478/ounit#transition-to-ounit2

The tests were [already passing](https://travis-ci.org/aantron/markup.ml/jobs/653738951#L293), just not in your setup because you must have been installing ounit2. I moved this repo to ounit2, as well.
