### ISSUE TITLE
Issues with build instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by glennsl** [aantron/markup.ml#51]
1. It says to run `make install` after cloning, but there's no `install` target in the root `Makefile`

2. It claims only `ounit` and `lwt` are needed, but there are now several other dependencies as well. `opam install --deps-only .` seems to install what's needed.

**Comment by aantron** [comment]
Yes, thanks for reporting. I'll edit the file. It doesn't reflect several build system changes that Markup has gone through over the years.
