### ISSUE TITLE
Odd formatting from Markup writer

### ISSUE THREAD

**Issue by johnwhitington** [aantron/markup.ml#80]
Hi.

I'm using Markup via Lambdasoup. If I parse and write this file, which the w3 validator says is valid...

```
<!doctype html>
<html lang=en>
  <head>
    <meta charset=utf-8>
    <title>Lambdasoup example</title>
  </head>
  <body>
    <p>Para 1 <br> More</p>
    <p>Para 2</p>
    <ul>
      <li>a</li>
      <li>b</li>
      <li>c</li>
    </ul>
  </body>
</html>
```

...I get this:

```
<!DOCTYPE html><html lang="en"><head>
    <meta charset="utf-8">
    <title>Lambdasoup example</title>
  </head>
  <body>
    <p>Para 1 <br> More</p>
    <p>Para 2</p>
    <ul>
      <li>a</li>
      <li>b</li>
      <li>c</li>
    </ul>
  

</body></html>
```

It seems that the input layout is being preserved to some extent - if I change the input, the output changes. But if this is so, why are some newlines missing from the beginning, and some new ones appearing at the end?

**Comment by johnwhitington** [comment]
I've had a quick look and I can't work out what project I was trying to use this in - I think I must have found another solution.

The whitespace above looks rather like whitespace characters are being accumulated somewhere, and then output almost right at the end. That's why it smelt like a bug.

Anyway, I'm closing this. Thanks for getting back to me.

**Comment by aantron** [comment]
I recall seeing this behavior when I originally developed Markup.ml, and those instances were according to the spec. As I recall, the parser ends up pushing whitespace chars towards the end of some tags where the parsing is especially special-cased, like `<html>` and `<body>`, but I don't recall the specifics.
